name = "velang"
version = "0.1.0"
defaultTargets = ["velang"]
testDriver = "Spec"

[[require]]
name = "VeIR"
git = "https://github.com/opencompl/veir.git"
rev = "9b0e199d3368264d4cf901bd7583ec7e5aa76568"

[[lean_lib]]
name = "Velang"

[[lean_lib]]
name = "Spec"
srcDir = "Tests"

[[lean_exe]]
name = "velang"
root = "Velang"
